### ISSUE TITLE
Disconnects and reconnects every 30 seconds

### ISSUE THREAD

**Issue by micrology** [yjs/y-websocket#24]
**Describe the bug**

The client disconnects and then reconnects from the websocket server every 30 seconds

**To Reproduce**

Set up a client running yjs. Intermittently, it will do something similar to this:

```
...
prism.js:209 21:00:34: connected to room CMD-HMM-NTO-XML
prism.js:209 21:01:06: disconnected from room CMD-HMM-NTO-XML
prism.js:209 21:01:07: connected to room CMD-HMM-NTO-XML
prism.js:209 21:01:39: disconnected from room CMD-HMM-NTO-XML
prism.js:209 21:01:40: connected to room CMD-HMM-NTO-XML
prism.js:209 21:02:12: disconnected from room CMD-HMM-NTO-XML
prism.js:209 21:02:13: connected to room CMD-HMM-NTO-XML
``` 
I have not discovered for certain what triggers this.  It *may* occur after resuming from a debugger break, but it does not happen every time.

**Environment**

Client code:
```
const wsProvider = new WebsocketProvider(
		'wss://cress.soc.surrey.ac.uk/wss',
		'prism' + room,
		doc
	);

wsProvider.on('status', (event) => {
		console.log(
			new Date().toLocaleTimeString() +
				': ' +
				event.status +
				(event.status == 'connected' ? ' to' : ' from') +
				' room ' +
				room
		); // logs "connected" or "disconnected"
	});
```

yjs: 13.2.0
y-websocket: 1.3.1
npm: 6.14.7
browser: Chrome 84
websocket server: y-websocket: 1.3.1 (slightly modified to accept wss:// connections)

**Comment by dmonad** [comment]
Hey @micrology 

It is expected that the server disconnects from the client after a debugger-break of a couple of seconds. y-websocket needs to send a ping or an awareness update (in almost all cases it's an awareness update) to the server. 

If you would use socket.io or something similar, they send a `ping` event to the client which the browser itself answers. With Yjs, I reuse the awareness update and only send a ping when no awareness update is sent (this reduces the message overhead a bit and is one of these performance perks that are probably completely unnecessary).

Can you reproduce this without creating a debugger break?

I've been running https://demos.yjs.dev/prosemirror/prosemirror.html for some time now and I'm not able to witness that the connection closes or that the `status` event fires.

**Comment by micrology** [comment]
Hi @dmonad 

I've been trying to narrow down the circumstances that give rise to this behaviour, but so far without success.  However, once it starts, it continues - even through a client reboot.  While I can understand that an interrupt such as a debugger break could yield a disconnect followed by a reconnect, once the connection has been re-established, why then does it continue to disconnect and reconnect every 30 seconds (when there is no debugger break or anything else at the client end causing loss of the heartbeat)?

To try to isolate the cause, I have set up two websocket-servers:  one that uses a reverse proxy to an instance of the wss:// code that I submitted as a PR, and one that uses your vanilla y-websocket code.  I get the problem using either route, so it is probably not my mods that have caused the issue.  I'll email you the two addresses.

If you can suggest anything I can try out or report back on, just let me know.

**Comment by micrology** [comment]
A change to util.js (see Memory leak? #23) seems to have cured this, so i am closing the issue.

**Comment by micrology** [comment]
Unfortunately, the issue persists, even with v1.3.6.  I get this in the console.log: 
```
prsm.js:206 21:28:56: disconnected from room TAD-MAM-KJF-IEM
prsm.js:206 21:28:57: connecting from room TAD-MAM-KJF-IEM
prsm.js:206 21:28:57: connected to room TAD-MAM-KJF-IEM
prsm.js:200 sync
prsm.js:200 sync
prsm.js:206 21:29:28: disconnected from room TAD-MAM-KJF-IEM
prsm.js:206 21:29:29: connecting from room TAD-MAM-KJF-IEM
prsm.js:206 21:29:29: connected to room TAD-MAM-KJF-IEM
prsm.js:200 sync
```
etc. repeating about every 30 seconds.
(The `sync` message is produced by:
```
	wsProvider.on('sync', () => {
		console.log('sync');
	});
```

This behaviour does not always occur, but does intermittently.  Once it starts, the only cure is to restart the client.

**Comment by AdventureBeard** [comment]
@micrology, are your clients setting their awareness state regularly? If they don't, the reconnect loop applies. I saw this behavior using y-prosemirror when I disabled its yCursorPlugin for debugging purposes. As soon as I re-enabled it (and consequently started sending awareness updates), the behavior ceased. I would think the ping sent from the server would count as a message w.r.t the idle-reconnect loop and wsLastMessageReceived, but I'm still reading through the code to get an understanding.

https://github.com/yjs/y-websocket/blob/114284c3492662172b7bba1e1f948411e546a922/src/y-websocket.js#L277

The reconnecting didn't bother me until I saw that closing the connection on the server didn't clean up all the memory allocated in the connection, leading to unbounded memory usage on my server for a single idling client. It seems like #23 may have not plugged all the leaks.

**Comment by micrology** [comment]
@AdventureBeard Your message prompted me to do some further investigation.  Your edit may indeed be a solution - I'll try it - but meanwhile here is what I found.

It has been a frustrating problem because the behaviour occurred intermittently, but I have now discovered an apparently infallible way to make it happen.

The trick is to start a websocket server, start a client, and then temporarily stop the server (while leaving the client running).  The easiest way to reproduce this is to start a local test server with `npx y-websocket-server` in a terminal window, run the client (connecting to port 1234), then stop the server (^C).  An inspector window for the client will show that the websocket connection has failed.  The client will try to reconnect (with status message ‘connecting’), but of course cannot because the server is down.  Now restart the websocket server.  From then on, every 30 seconds (approx.), the inspector window will show a sequence of ‘connecting/connected/disconnected’ messages.  This shows that the y-websocket provider has connected successfully to the restarted server, but then times out and disconnects. 

In more detail (line numbers for `y-websocket.js`), the `WebsocketProvider` class constructor calls `setInterval` (line 273) that every 3 seconds checks whether the time since the last  message received (`wsLastMessageReceived`) exceeds `messageReconnectTimeout` (which is 30000 mS, 30 seconds).  If so, the websocket is closed (line 277), generating a ‘disconnected’ message (line 104). After closure, a timeout is set (line 113) and when the timeout expires, a new provider is created (in `setupWS()`, line 81).  An event is passed to `websocket.onopen()` (line 115) which resets `wsLastMessageReceived` to the current time and another event is passed to `websocket.onmessage(),` which again sets `wsLastMessageReceived `to the current time.  But then no more message events are generated and so `wsLastMessageReceived` is not updated any more until the check in line 273 determines that the time since the last message exceeds the 30 second timeout.  The websocket is closed (line 227) and the cycle repeats.

If my logic is correct, the puzzle then moves to `server.js` - why is it not generating message events to update the `wsLastMessageReceived`?  This is where I have got to so far.

**Comment by micrology** [comment]
@AdventureBeard following up your suggestion about increasing `messageReconnectTimeout`:  I changed it to 40000, and then started, stopped and restarted the server as described above, and unfortunately that change does not cure the reconnecting behaviour.  :-(  A pity.

**Comment by micrology** [comment]
Continuing the saga: After stopping and restarting the server, I have confirmed that no more `messageAwareness` messages are received by the client, and hence the connection times out (when it is running normally, a `messageAwareness` message appears about every 15 seconds).  The messages are generated in `y-protocols/awareness.js` where there is a `setInterval` (line 55) that calls `setLocalState` (which as a side  effect emits `messageAwareness` messages) when (a) the local state is not null and (b) the awareness clock setting is older than 15 secs.  However, when the server has been restarted, the local state is lost and is null, so condition (a) is false, `setLocalState` is not called and the awareness message is not emitted.

The next problem to solve in this detective hunt  is how the local state is lost when the server restarts....

**Comment by micrology** [comment]
Final episode of this saga (possibly?):  The local state is lost when the server stops because `websocket.onclose` calls `awarenessProtocol.removeAwarenessStates` (line 105 in `y-websocket.js`), which deletes all the awareness states.  If one removes that line of code, stopping and restarting the server does not trigger the recycling behaviour and all works as expected.  There may be some circumstances in which it is advisable to call `awarenessProtocol.removeAwarenessStates` on close, but I can't think of any (it is also called at `beforeunload` (line 275), but that is as it should be).  Maybe @dmonad could advise?  

Before deleting this line of code, when the the timeout expired and server was restarted , a new instance of `websocket` is created (`y-websocket.js`, line 82), but the old one is not destroyed.  Since this used to happen every 30 seconds, one can see why, over time, there seemed to be a memory leak.

**Comment by micrology** [comment]
For the record, [y-websocket 1.3.8](https://github.com/yjs/y-websocket/commit/63af0c0fc0589a20dd98ca5bb3659e45ba5fac38) resolves this issue.

**Comment by dmonad** [comment]
That's great to hear! Thanks, I was about to check this issue again. 

You were on to something with "awarenessProtocol.removeAwarenessStates (line 105 in y-websocket.js)". 

The awareness states were not correctly removed. The local one should have been kept. #40 

Furthermore, there was a memory leak related to awareness that I resolved in Yjs@13.4.6. The awareness instance was never destroyed, so the timeout was called all the time and consumed memory (depending on the amount of sessions created). 

Hope this also fixes your memory leak.

**Comment by micrology** [comment]
Super!  Delighted that this long-standing mystery is now solved.

Nigel



Professor Nigel Gilbert, CBE, ScD, FREng, FAcSS, Professor of Sociology,
University of Surrey, Guildford GU2 7XH, UK. +44 (0)1483 689173

**Comment by rickhall** [comment]
I am developing a web app and have started to see this behavior. I haven't figured out how to recreate it, but it does reappear every so often and is the exact behavior described here (i.e., once it starts disconnecting/reconnecting everything 30 seconds then it is sort of sticky and continues to do that until I kill the server and completely refresh the client). I'm on all the latest versions, so I'm not sure why I'm see this issue if it has been fixed.

**Comment by rickhall** [comment]
After some more investigating, I still can't consistently reproduce the issue, but if I just keep exercising my UI which allows me to open and close yjs docs via WebsocketProvider, then I can eventually get it to start misbehaving.

After instrumenting the code, I can see when it gets into this state that subsequent WebsocketProviders are no longer receiving any messages to keep their connection alive.

I have an original WebsocketProvider for an index document that I keep open the entire time and it *does* keep getting messages to keep its connection alive, but for some reason no subsequent providers ever receive  any messages.

**Comment by rickhall** [comment]
After further investigation, I don't believe my issue is related to this one afterall. The reason why I am not getting awareness messages is because the documents weren't getting set up correctly. It seems the issuing I'm seeing is a symptom of some other issue where the changes I am making in my local document are not properly getting synchronized with the server. Long story short, I'm not sure what is going on, but for now I'll assume the issue is on my end.
